This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./Relatorio-DEE.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Relatorio-DEE.acn....done (94 entries accepted, 0 rejected).
Sorting entries....done (656 comparisons).
Generating output file Relatorio-DEE.acr....done (100 lines written, 0 warnings).
Output written in Relatorio-DEE.acr.
Transcript written in Relatorio-DEE.alg.
